package xmlization_test

// This code has been automatically generated by:
// _dev_scripts/test_codegen/generate_xmlization_of_concrete_classes_test.py
// Do NOT edit or append.

import (
	"bytes"
	"encoding/xml"
	"fmt"
	aastesting "github.com/aas-core-works/aas-core3.0-golang/aastesting"
	aasxmlization "github.com/aas-core-works/aas-core3.0-golang/xmlization"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

func TestExtensionRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"Extension",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestExtensionDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"Extension",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestAdministrativeInformationRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"AdministrativeInformation",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestAdministrativeInformationDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"AdministrativeInformation",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestQualifierRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"Qualifier",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestQualifierDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"Qualifier",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestAssetAdministrationShellRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"AssetAdministrationShell",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestAssetAdministrationShellDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"AssetAdministrationShell",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestAssetInformationRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"AssetInformation",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestAssetInformationDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"AssetInformation",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestResourceRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"Resource",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestResourceDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"Resource",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestSpecificAssetIDRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"SpecificAssetId",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestSpecificAssetIDDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"SpecificAssetId",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestSubmodelRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"Submodel",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestSubmodelDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"Submodel",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestRelationshipElementRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"RelationshipElement",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestRelationshipElementDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"RelationshipElement",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestSubmodelElementListRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"SubmodelElementList",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestSubmodelElementListDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"SubmodelElementList",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestSubmodelElementCollectionRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"SubmodelElementCollection",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestSubmodelElementCollectionDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"SubmodelElementCollection",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestPropertyRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"Property",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestPropertyDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"Property",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestMultiLanguagePropertyRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"MultiLanguageProperty",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestMultiLanguagePropertyDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"MultiLanguageProperty",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestRangeRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"Range",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestRangeDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"Range",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestReferenceElementRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"ReferenceElement",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestReferenceElementDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"ReferenceElement",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestBlobRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"Blob",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestBlobDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"Blob",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestFileRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"File",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestFileDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"File",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestAnnotatedRelationshipElementRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"AnnotatedRelationshipElement",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestAnnotatedRelationshipElementDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"AnnotatedRelationshipElement",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestEntityRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"Entity",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestEntityDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"Entity",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestEventPayloadRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"SelfContained",
			"Expected",
			"EventPayload",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEventPayload(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestEventPayloadDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"SelfContained",
				"Unexpected",
				cause,
				"EventPayload",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestBasicEventElementRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"BasicEventElement",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestBasicEventElementDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"BasicEventElement",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestOperationRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"Operation",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestOperationDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"Operation",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestOperationVariableRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"OperationVariable",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestOperationVariableDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"OperationVariable",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestCapabilityRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"Capability",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestCapabilityDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"Capability",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestConceptDescriptionRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"ConceptDescription",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestConceptDescriptionDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"ConceptDescription",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestReferenceRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"Reference",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestReferenceDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"Reference",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestKeyRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"Key",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestKeyDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"Key",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestLangStringNameTypeRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"LangStringNameType",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestLangStringNameTypeDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"LangStringNameType",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestLangStringTextTypeRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"LangStringTextType",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestLangStringTextTypeDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"LangStringTextType",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestEnvironmentRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"SelfContained",
			"Expected",
			"Environment",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestEnvironmentDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"SelfContained",
				"Unexpected",
				cause,
				"Environment",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestEmbeddedDataSpecificationRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"EmbeddedDataSpecification",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestEmbeddedDataSpecificationDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"EmbeddedDataSpecification",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestLevelTypeRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"LevelType",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestLevelTypeDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"LevelType",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestValueReferencePairRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"ValueReferencePair",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestValueReferencePairDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"ValueReferencePair",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestValueListRoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"ValueList",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestValueListDeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"ValueList",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestLangStringPreferredNameTypeIEC61360RoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"LangStringPreferredNameTypeIec61360",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestLangStringPreferredNameTypeIEC61360DeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"LangStringPreferredNameTypeIec61360",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestLangStringShortNameTypeIEC61360RoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"LangStringShortNameTypeIec61360",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestLangStringShortNameTypeIEC61360DeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"LangStringShortNameTypeIec61360",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestLangStringDefinitionTypeIEC61360RoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"LangStringDefinitionTypeIec61360",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestLangStringDefinitionTypeIEC61360DeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"LangStringDefinitionTypeIec61360",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestDataSpecificationIEC61360RoundTripOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Xml",
			"ContainedInEnvironment",
			"Expected",
			"DataSpecificationIec61360",
		),
		".xml",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		bb, err := os.ReadFile(pth)
		if err != nil {
			t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
			return
		}
		text := string(bb)

		decoder := xml.NewDecoder(strings.NewReader(text))

		deserialized, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
		ok := assertNoDeserializationError(t, deseriaErr, pth)
		if !ok {
			return
		}

		buf := &bytes.Buffer{}
		encoder := xml.NewEncoder(buf)
		encoder.Indent("", "\t")

		seriaErr := aasxmlization.Marshal(encoder, deserialized, true)
		ok = assertNoSerializationError(t, seriaErr, pth)
		if !ok {
			return
		}

		roundTrip := string(buf.Bytes())

		ok = assertSerializationEqualsDeserialization(
			t,
			text,
			roundTrip,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestDataSpecificationIEC61360DeserializationFail(t *testing.T) {
	for _, cause := range causesForDeserializationFailure {
		pths := aastesting.FindFilesBySuffixRecursively(
			filepath.Join(
				aastesting.TestDataDir,
				"Xml",
				"ContainedInEnvironment",
				"Unexpected",
				cause,
				"DataSpecificationIec61360",
			),
			".xml",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"DeserializationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".error",
			)

			bb, err := os.ReadFile(pth)
			if err != nil {
				t.Fatalf("Failed to read the file %s: %s", pth, err.Error())
				return
			}
			text := string(bb)

			decoder := xml.NewDecoder(strings.NewReader(text))

			_, deseriaErr := aasxmlization.UnmarshalEnvironment(decoder)
			ok := assertIsDeserializationErrorAndEqualsExpectedOrRecord(
				t, deseriaErr, pth, expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

// This code has been automatically generated by:
// _dev_scripts/test_codegen/generate_xmlization_of_concrete_classes_test.py
// Do NOT edit or append.
